src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contract_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $offer_number;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $investor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $object_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $building_category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $safety;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getContractNumber(): ?string
    {
        return $this->contract_number;
    }

    public function setContractNumber(?string $contract_number): self
    {
        $this->contract_number = $contract_number;

        return $this;
    }

    public function getOfferNumber(): ?string
    {
        return $this->offer_number;
    }

    public function setOfferNumber(?string $offer_number): self
    {
        $this->offer_number = $offer_number;

        return $this;
    }

    public function getInvestor(): ?int
    {
        return $this->investor;
    }

    public function setInvestor(?int $investor): self
    {
        $this->investor = $investor;

        return $this;
    }

    public function getObjectType(): ?string
    {
        return $this->object_type;
    }

    public function setObjectType(?string $object_type): self
    {
        $this->object_type = $object_type;

        return $this;
    }

    public function getBuildingCategory(): ?string
    {
        return $this->building_category;
    }

    public function setBuildingCategory(?string $building_category): self
    {
        $this->building_category = $building_category;

        return $this;
    }

    public function getSafety(): ?string
    {
        return $this->safety;
    }

    public function setSafety(?string $safety): self
    {
        $this->safety = $safety;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('number')
            ->add('contract_number')
            ->add('offer_number')
            ->add('investor')
            ->add('object_type')
            ->add('building_category')
            ->add('safety')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    /**
     * @Route("/orders", name="order_index", methods={"GET"})
     */
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    /**
     * @Route("/order/new", name="order_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/new.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/order/{id}", name="order_show", methods={"GET"})
     */
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/order/{id}/edit", name="order_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Order $order): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/order/{id}", name="order_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index');
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Number</th>
                <th>Contract_number</th>
                <th>Offer_number</th>
                <th>Investor</th>
                <th>Object_type</th>
                <th>Building_category</th>
                <th>Safety</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.number }}</td>
                <td>{{ order.contractNumber }}</td>
                <td>{{ order.offerNumber }}</td>
                <td>{{ order.investor }}</td>
                <td>{{ order.objectType }}</td>
                <td>{{ order.buildingCategory }}</td>
                <td>{{ order.safety }}</td>
                <td>
                    <a href="{{ path('order_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('order_new') }}">Create new</a>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order/_form.html.twig') }}

    <a href="{{ path('order_index') }}">back to list</a>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ order.number }}</td>
            </tr>
            <tr>
                <th>Contract_number</th>
                <td>{{ order.contractNumber }}</td>
            </tr>
            <tr>
                <th>Offer_number</th>
                <td>{{ order.offerNumber }}</td>
            </tr>
            <tr>
                <th>Investor</th>
                <td>{{ order.investor }}</td>
            </tr>
            <tr>
                <th>Object_type</th>
                <td>{{ order.objectType }}</td>
            </tr>
            <tr>
                <th>Building_category</th>
                <td>{{ order.buildingCategory }}</td>
            </tr>
            <tr>
                <th>Safety</th>
                <td>{{ order.safety }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('order_index') }}">back to list</a>

    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}